Notebook for analyzing results.

In [231]:
import pandas as pd
import seaborn as sns

import matplotlib
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42

In [232]:
df = pd.read_json('results.json', lines=True)
df['no_fail'] = df['no_fail'].fillna(1)
cols = {'t': 'Time',
        'no_fail': 'No Fail',
        'weight_acc': 'Weighted Acc.',
        'edr': 'EDR',
        'ttd': 'TTD',
        'env': 'Environment',
        'method': 'Method'
}
df = df.rename(columns=cols)
df = df.replace({
    'cd': 'CD',
    'cd_ae': 'CD-AE',
    'dist': 'Dist',
    'ae_rec': 'AE-REC',
    'cd_rp': 'CD-RP'
})
df = df.replace({
    'inv_pend': 'Inv. Pend.',
    'hopper': 'Hopper',
    'half_cheetah': 'Half Cheetah',
    'ant': 'Ant',
    'humanoid': 'Humanoid'
})

drop_rows = [0, 1, 8, 9, 10, 12, 13, 14, 16, 17, 18, 23]
df

,Method,Environment,enc,No Fail,hid,lat,proj,deg,tpr,tnr,bal_acc,Weighted Acc.,TTD,EDR,Time
0,CD,Inv. Pend.,None,1.0,NaN,NaN,NaN,4,0.997912,0.848369,0.923140,0.920,2.534519,0.625523,0.118126
1,CD,Inv. Pend.,None,1.0,NaN,NaN,NaN,5,1.000000,0.844530,0.922265,0.919,2.459916,0.636743,0.264336
2,CD,Inv. Pend.,None,1.0,NaN,NaN,NaN,6,1.000000,0.813820,0.906910,0.903,2.731315,0.645094,0.553434
3,CD-AE,Inv. Pend.,version_0,1.0,64.0,5.0,NaN,6,0.997912,0.817658,0.907785,0.904,2.459205,0.627615,0.539476
4,CD-AE,Inv. Pend.,version_1,0.0,64.0,5.0,NaN,6,1.000000,0.821497,0.910749,0.907,2.672860,0.632568,0.534909
5,Dist,Inv. Pend.,None,1.0,NaN,NaN,NaN,3,1.000000,0.585413,0.792706,0.784,1.892067,0.584551,0.104143
6,AE-REC,Inv. Pend.,version_0,1.0,64.0,5.0,NaN,3,0.997912,0.752399,0.875156,0.870,0.896653,0.487448,0.007087
7,CD-RP,Inv. Pend.,None,1.0,NaN,NaN,5.0,6,0.997912,0.794626,0.896269,0.892,1.132845,0.527197,0.534130
8,CD,Hopper,None,1.0,NaN,NaN,NaN,1,1.000000,0.596708,0.798354,0.902,19.878600,0.985469,0.024495
9,CD,Hopper,None,1.0,NaN,NaN,NaN,2,1.000000,0.814815,0.907407,0.955,24.314531,1.000000,0.175362
10,CD,Hopper,None,1.0,NaN,NaN,NaN,3,1.000000,0.888889,0.944444,0.973,23.210172,0.998679,0.909973
11,CD,Hopper,None,1.0,NaN,NaN,NaN,4,1.000000,0.876543,0.938272,0.970,22.042404,1.000000,5.352221
12,CD-AE,Hopper,version_0,1.0,64.0,5.0,NaN,3,0.998679,0.695473,0.847076,0.925,17.919709,0.989418,0.052403
13,CD-AE,Hopper,version_0,1.0,64.0,5.0,NaN,4,0.998679,0.736626,0.867652,0.935,20.350926,0.990741,0.117089
14,CD-AE,Hopper,version_0,1.0,64.0,5.0,NaN,5,0.998679,0.773663,0.886171,0.944,20.837698,0.996032,0.255540
15,CD-AE,Hopper,version_0,1.0,64.0,5.0,NaN,6,1.000000,0.769547,0.884774,0.944,21.381902,0.998679,0.556720
16,CD-AE,Hopper,version_1,0.0,64.0,5.0,NaN,3,0.998679,0.683128,0.840903,0.922,19.599603,0.989418,0.051557
17,CD-AE,Hopper,version_1,0.0,64.0,5.0,NaN,4,0.998679,0.703704,0.851191,0.927,21.081085,0.989418,0.118998
18,CD-AE,Hopper,version_1,0.0,64.0,5.0,NaN,5,1.000000,0.695473,0.847737,0.926,23.305284,0.998679,0.255175
19,CD-AE,Hopper,version_1,0.0,64.0,5.0,NaN,6,1.000000,0.728395,0.864198,0.934,23.292074,0.997358,0.546287
20,Dist,Hopper,None,1.0,NaN,NaN,NaN,3,1.000000,0.292181,0.646091,0.828,31.405680,1.000000,0.047116
21,AE-REC,Hopper,version_0,1.0,64.0,5.0,NaN,3,0.997358,0.765432,0.881395,0.941,13.200397,0.985430,0.008921
22,CD-RP,Hopper,None,1.0,NaN,NaN,5.0,6,0.998679,0.806584,0.902632,0.952,19.144577,0.989418,0.552038
23,CD-RP,Hopper,None,1.0,NaN,NaN,10.0,4,1.000000,0.802469,0.901235,0.952,24.045046,1.000000,1.292096
24,CD-AE,Half Cheetah,version_0,1.0,64.0,10.0,NaN,4,0.750000,0.848684,0.799342,0.825,9.886667,0.716667,1.295670
25,CD-AE,Half Cheetah,version_1,0.0,64.0,10.0,NaN,4,0.758333,0.857895,0.808114,0.834,10.489560,0.725275,1.310010
26,Dist,Half Cheetah,None,1.0,NaN,NaN,NaN,3,0.787500,0.756579,0.772039,0.764,13.972487,0.798942,0.159488
27,AE-REC,Half Cheetah,version_0,1.0,64.0,10.0,NaN,3,0.741667,0.867105,0.804386,0.837,9.135393,0.674157,0.010829
28,CD-RP,Half Cheetah,None,1.0,NaN,NaN,10.0,4,0.845833,0.864474,0.855154,0.860,10.722167,0.694581,1.310049
29,CD-AE,Ant,version_0,1.0,128.0,30.0,NaN,2,0.925532,0.722958,0.824245,0.742,14.955172,0.701149,1.049501
30,CD-AE,Ant,version_1,0.0,128.0,30.0,NaN,2,0.936170,0.733996,0.835083,0.753,14.648864,0.693182,1.113574
31,Dist,Ant,None,1.0,NaN,NaN,NaN,3,0.989362,0.583885,0.786623,0.622,15.301075,0.645161,0.203416
32,AE-REC,Ant,version_0,1.0,128.0,30.0,NaN,3,0.936170,0.738411,0.837290,0.757,14.373864,0.693182,0.034523
33,CD-RP,Ant,None,1.0,NaN,NaN,30.0,2,0.946809,0.718543,0.832676,0.740,16.912360,0.730337,1.038387
34,CD-AE,Humanoid,version_0,1.0,128.0,30.0,NaN,2,0.997494,0.715474,0.856484,0.828,14.484422,0.693467,1.096149
35,CD-AE,Humanoid,version_1,0.0,128.0,30.0,NaN,2,0.997494,0.693844,0.845669,0.815,15.182915,0.738693,1.108525
36,Dist,Humanoid,None,1.0,NaN,NaN,NaN,3,1.000000,0.429285,0.714642,0.657,22.311529,0.884712,0.200878
37,AE-REC,Humanoid,version_0,1.0,128.0,30.0,NaN,3,0.992481,0.697171,0.844826,0.815,10.754040,0.527778,0.081524
38,CD-RP,Humanoid,None,1.0,NaN,NaN,30.0,2,1.000000,0.673877,0.836938,0.804,14.141103,0.754386,1.138454

In [233]:
df = df.drop(drop_rows)
df = df[df['No Fail'] == 1.0]
df

,Method,Environment,enc,No Fail,hid,lat,proj,deg,tpr,tnr,bal_acc,Weighted Acc.,TTD,EDR,Time
2,CD,Inv. Pend.,None,1.0,NaN,NaN,NaN,6,1.000000,0.813820,0.906910,0.903,2.731315,0.645094,0.553434
3,CD-AE,Inv. Pend.,version_0,1.0,64.0,5.0,NaN,6,0.997912,0.817658,0.907785,0.904,2.459205,0.627615,0.539476
5,Dist,Inv. Pend.,None,1.0,NaN,NaN,NaN,3,1.000000,0.585413,0.792706,0.784,1.892067,0.584551,0.104143
6,AE-REC,Inv. Pend.,version_0,1.0,64.0,5.0,NaN,3,0.997912,0.752399,0.875156,0.870,0.896653,0.487448,0.007087
7,CD-RP,Inv. Pend.,None,1.0,NaN,NaN,5.0,6,0.997912,0.794626,0.896269,0.892,1.132845,0.527197,0.534130
11,CD,Hopper,None,1.0,NaN,NaN,NaN,4,1.000000,0.876543,0.938272,0.970,22.042404,1.000000,5.352221
15,CD-AE,Hopper,version_0,1.0,64.0,5.0,NaN,6,1.000000,0.769547,0.884774,0.944,21.381902,0.998679,0.556720
20,Dist,Hopper,None,1.0,NaN,NaN,NaN,3,1.000000,0.292181,0.646091,0.828,31.405680,1.000000,0.047116
21,AE-REC,Hopper,version_0,1.0,64.0,5.0,NaN,3,0.997358,0.765432,0.881395,0.941,13.200397,0.985430,0.008921
22,CD-RP,Hopper,None,1.0,NaN,NaN,5.0,6,0.998679,0.806584,0.902632,0.952,19.144577,0.989418,0.552038
24,CD-AE,Half Cheetah,version_0,1.0,64.0,10.0,NaN,4,0.750000,0.848684,0.799342,0.825,9.886667,0.716667,1.295670
26,Dist,Half Cheetah,None,1.0,NaN,NaN,NaN,3,0.787500,0.756579,0.772039,0.764,13.972487,0.798942,0.159488
27,AE-REC,Half Cheetah,version_0,1.0,64.0,10.0,NaN,3,0.741667,0.867105,0.804386,0.837,9.135393,0.674157,0.010829
28,CD-RP,Half Cheetah,None,1.0,NaN,NaN,10.0,4,0.845833,0.864474,0.855154,0.860,10.722167,0.694581,1.310049
29,CD-AE,Ant,version_0,1.0,128.0,30.0,NaN,2,0.925532,0.722958,0.824245,0.742,14.955172,0.701149,1.049501
31,Dist,Ant,None,1.0,NaN,NaN,NaN,3,0.989362,0.583885,0.786623,0.622,15.301075,0.645161,0.203416
32,AE-REC,Ant,version_0,1.0,128.0,30.0,NaN,3,0.936170,0.738411,0.837290,0.757,14.373864,0.693182,0.034523
33,CD-RP,Ant,None,1.0,NaN,NaN,30.0,2,0.946809,0.718543,0.832676,0.740,16.912360,0.730337,1.038387
34,CD-AE,Humanoid,version_0,1.0,128.0,30.0,NaN,2,0.997494,0.715474,0.856484,0.828,14.484422,0.693467,1.096149
36,Dist,Humanoid,None,1.0,NaN,NaN,NaN,3,1.000000,0.429285,0.714642,0.657,22.311529,0.884712,0.200878
37,AE-REC,Humanoid,version_0,1.0,128.0,30.0,NaN,3,0.992481,0.697171,0.844826,0.815,10.754040,0.527778,0.081524
38,CD-RP,Humanoid,None,1.0,NaN,NaN,30.0,2,1.000000,0.673877,0.836938,0.804,14.141103,0.754386,1.138454

In [234]:
metrics = ['Weighted Acc.', 'EDR', 'TTD', 'Time']
df = df.set_index(['Environment', 'Method'])[metrics]
df

                     Weighted Acc.       EDR        TTD      Time
Environment  Method
Inv. Pend.   CD              0.903  0.645094   2.731315  0.553434
             CD-AE           0.904  0.627615   2.459205  0.539476
             Dist            0.784  0.584551   1.892067  0.104143
             AE-REC          0.870  0.487448   0.896653  0.007087
             CD-RP           0.892  0.527197   1.132845  0.534130
Hopper       CD              0.970  1.000000  22.042404  5.352221
             CD-AE           0.944  0.998679  21.381902  0.556720
             Dist            0.828  1.000000  31.405680  0.047116
             AE-REC          0.941  0.985430  13.200397  0.008921
             CD-RP           0.952  0.989418  19.144577  0.552038
Half Cheetah CD-AE           0.825  0.716667   9.886667  1.295670
             Dist            0.764  0.798942  13.972487  0.159488
             AE-REC          0.837  0.674157   9.135393  0.010829
             CD-RP           0.860  0.694581  10.722167  1.310049
Ant          CD-AE           0.742  0.701149  14.955172  1.049501
             Dist            0.622  0.645161  15.301075  0.203416
             AE-REC          0.757  0.693182  14.373864  0.034523
             CD-RP           0.740  0.730337  16.912360  1.038387
Humanoid     CD-AE           0.828  0.693467  14.484422  1.096149
             Dist            0.657  0.884712  22.311529  0.200878
             AE-REC          0.815  0.527778  10.754040  0.081524
             CD-RP           0.804  0.754386  14.141103  1.138454

In [235]:
def highlight_group(group):
    out = group.copy()

    # Convert to string first so we can safely insert LaTeX commands
    for col in ["Weighted Acc.", "EDR", "TTD", "Time"]:
        out[col] = group[col].map(lambda v: f"{v:.3f}")

    # Bold maxima
    for col in ["Weighted Acc.", "EDR", "TTD"]:
        idxmax = group[col].idxmax()
        out.loc[idxmax, col] = f"\\textbf{{{group.loc[idxmax, col]:.3f}}}"

    # Bold minimum for Time
    idxmin = group["Time"].idxmin()
    out.loc[idxmin, "Time"] = f"\\textbf{{{group.loc[idxmin, 'Time']:.3f}}}"

    return out

df_bold = (
    df.groupby(level=0, group_keys=False, sort=False)
      .apply(highlight_group)
)

latex_table = df_bold.to_latex(
    escape=False,
    multirow=True,
    multicolumn_format="c"
)

In [236]:
print(latex_table)

\begin{tabular}{llllll}
\toprule
 &  & Weighted Acc. & EDR & TTD & Time \\
Environment & Method &  &  &  &  \\
\midrule
\multirow[t]{5}{*}{Inv. Pend.} & CD & 0.903 & \textbf{0.645} & \textbf{2.731} & 0.553 \\
 & CD-AE & \textbf{0.904} & 0.628 & 2.459 & 0.539 \\
 & Dist & 0.784 & 0.585 & 1.892 & 0.104 \\
 & AE-REC & 0.870 & 0.487 & 0.897 & \textbf{0.007} \\
 & CD-RP & 0.892 & 0.527 & 1.133 & 0.534 \\
\cline{1-6}
\multirow[t]{5}{*}{Hopper} & CD & \textbf{0.970} & \textbf{1.000} & 22.042 & 5.352 \\
 & CD-AE & 0.944 & 0.999 & 21.382 & 0.557 \\
 & Dist & 0.828 & 1.000 & \textbf{31.406} & 0.047 \\
 & AE-REC & 0.941 & 0.985 & 13.200 & \textbf{0.009} \\
 & CD-RP & 0.952 & 0.989 & 19.145 & 0.552 \\
\cline{1-6}
\multirow[t]{4}{*}{Half Cheetah} & CD-AE & 0.825 & 0.717 & 9.887 & 1.296 \\
 & Dist & 0.764 & \textbf{0.799} & \textbf{13.972} & 0.159 \\
 & AE-REC & 0.837 & 0.674 & 9.135 & \textbf{0.011} \\
 & CD-RP & \textbf{0.860} & 0.695 & 10.722 & 1.310 \\
\cline{1-6}
\multirow[t]{4}{*}{Ant} & CD-AE & 0.742 & 0.701 & 14.955 & 1.050 \\
 & Dist & 0.622 & 0.645 & 15.301 & 0.203 \\
 & AE-REC & \textbf{0.757} & 0.693 & 14.374 & \textbf{0.035} \\
 & CD-RP & 0.740 & \textbf{0.730} & \textbf{16.912} & 1.038 \\
\cline{1-6}
\multirow[t]{4}{*}{Humanoid} & CD-AE & \textbf{0.828} & 0.693 & 14.484 & 1.096 \\
 & Dist & 0.657 & \textbf{0.885} & \textbf{22.312} & 0.201 \\
 & AE-REC & 0.815 & 0.528 & 10.754 & \textbf{0.082} \\
 & CD-RP & 0.804 & 0.754 & 14.141 & 1.138 \\
\cline{1-6}
\bottomrule
\end{tabular}

In [217]:
latex_table = df.to_latex(
    multicolumn=True,
    multicolumn_format="c",
    float_format="%.3f",
    escape=False
)

print(latex_table)

\begin{tabular}{llrrrr}
\toprule
 &  & Weighted Acc. & EDR & TTD & Time \\
Environment & Method &  &  &  &  \\
\midrule
\multirow[t]{5}{*}{Inv. Pend.} & CD & 0.903 & 0.645 & 2.731 & 2.497 \\
 & CD-AE & 0.904 & 0.628 & 2.459 & 2.467 \\
 & Dist & 0.784 & 0.585 & 1.892 & 0.100 \\
 & AE-REC & 0.870 & 0.487 & 0.897 & 0.007 \\
 & CD-RP & 0.892 & 0.527 & 1.133 & 2.115 \\
\cline{1-6}
\multirow[t]{5}{*}{Hopper} & CD & 0.970 & 1.000 & 22.042 & 11.579 \\
 & CD-AE & 0.944 & 0.999 & 21.382 & 1.290 \\
 & Dist & 0.828 & 1.000 & 31.406 & 0.048 \\
 & AE-REC & 0.941 & 0.985 & 13.200 & 0.009 \\
 & CD-RP & 0.952 & 0.989 & 19.145 & 1.271 \\
\cline{1-6}
\multirow[t]{4}{*}{Half Cheetah} & CD-AE & 0.825 & 0.717 & 9.887 & 6.488 \\
 & Dist & 0.764 & 0.799 & 13.972 & 0.164 \\
 & AE-REC & 0.837 & 0.674 & 9.135 & 0.012 \\
 & CD-RP & 0.860 & 0.695 & 10.722 & 4.918 \\
\cline{1-6}
\multirow[t]{4}{*}{Ant} & CD-AE & 0.742 & 0.701 & 14.955 & 2.117 \\
 & Dist & 0.622 & 0.645 & 15.301 & 0.201 \\
 & AE-REC & 0.757 & 0.693 & 14.374 & 0.032 \\
 & CD-RP & 0.740 & 0.730 & 16.912 & 2.144 \\
\cline{1-6}
\multirow[t]{4}{*}{Humanoid} & CD-AE & 0.828 & 0.693 & 14.484 & 1.832 \\
 & Dist & 0.657 & 0.885 & 22.312 & 0.198 \\
 & AE-REC & 0.815 & 0.528 & 10.754 & 0.090 \\
 & CD-RP & 0.804 & 0.754 & 14.141 & 1.896 \\
\cline{1-6}
\bottomrule
\end{tabular}

In [182]:
print(latex_table)

\begin{tabular}{llllll}
\toprule
 &  & 0 & 1 & 2 & 3 \\
Environment & Method &  &  &  &  \\
\midrule
\multirow[t]{5}{*}{Inv. Pend.} & CD & 0.90 & 0.65 & \textbf{2.73} & 2.50 \\
 & CD-AE & 0.90 & 0.63 & 2.46 & \textbf{2.47} \\
 & Dist & 0.78 & 0.58 & \textbf{1.89} & 0.10 \\
 & AE-REC & 0.87 & 0.49 & \textbf{0.90} & 0.01 \\
 & CD-RP & 0.89 & 0.53 & 1.13 & \textbf{2.12} \\
\cline{1-6}
\multirow[t]{5}{*}{Hopper} & CD & 0.97 & 1.00 & \textbf{22.04} & 11.58 \\
 & CD-AE & 0.94 & 1.00 & \textbf{21.38} & 1.29 \\
 & Dist & 0.83 & 1.00 & \textbf{31.41} & 0.05 \\
 & AE-REC & 0.94 & 0.99 & \textbf{13.20} & 0.01 \\
 & CD-RP & 0.95 & 0.99 & \textbf{19.14} & 1.27 \\
\cline{1-6}
\multirow[t]{4}{*}{Half Cheetah} & CD-AE & 0.83 & 0.72 & \textbf{9.89} & 6.49 \\
 & Dist & 0.76 & 0.80 & \textbf{13.97} & 0.16 \\
 & AE-REC & 0.84 & 0.67 & \textbf{9.14} & 0.01 \\
 & CD-RP & 0.86 & 0.69 & \textbf{10.72} & 4.92 \\
\cline{1-6}
\multirow[t]{4}{*}{Ant} & CD-AE & 0.74 & 0.70 & \textbf{14.96} & 2.12 \\
 & Dist & 0.62 & 0.65 & \textbf{15.30} & 0.20 \\
 & AE-REC & 0.76 & 0.69 & \textbf{14.37} & 0.03 \\
 & CD-RP & 0.74 & 0.73 & \textbf{16.91} & 2.14 \\
\cline{1-6}
\multirow[t]{4}{*}{Humanoid} & CD-AE & 0.83 & 0.69 & \textbf{14.48} & 1.83 \\
 & Dist & 0.66 & 0.88 & \textbf{22.31} & 0.20 \\
 & AE-REC & 0.82 & 0.53 & \textbf{10.75} & 0.09 \\
 & CD-RP & 0.80 & 0.75 & \textbf{14.14} & 1.90 \\
\cline{1-6}
\bottomrule
\end{tabular}

In [81]:
df[(df['env'] == 'hopper') & (df['method'] == 'cd')].plot('deg', 'ttd', marker='s')

KeyError: 'env'